# if yamal key has empty value, it will get value from env instead with acording key name (ex. server.addr => server_addr) 
app:
  profile: dev
  token-secret: my-secret
server:
  addr: :8080  
database:
  host: localhost
  port: 5432
  user: postgres
  password: 123456
  dbname: app
  sslmode: disable
  timezone: Asia/Bangkok